/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week_7;

import java.util.ArrayList;

/**
 *
 * @author olive
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form BankSystemGui
     */
    public Main() {
        loadData();
        initComponents();
        
        index = 0;
        AccountNoView.setText(accountList.get(index).getAccountNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountPannel = new javax.swing.JPanel();
        AccountNext = new javax.swing.JButton();
        AccountView = new javax.swing.JButton();
        AccountPrevious = new javax.swing.JButton();
        AccountNoView = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Deposit = new javax.swing.JPanel();
        DepositConfirm = new javax.swing.JButton();
        DepositCancel = new javax.swing.JButton();
        depositTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Withdraw = new javax.swing.JPanel();
        WithdrawConfirm = new javax.swing.JButton();
        WithdrawCancel = new javax.swing.JButton();
        withdrawTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        QuitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AccountPannel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bank Accounts"));
        AccountPannel.setName("BankAccounts"); // NOI18N

        AccountNext.setText("Next");
        AccountNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountNextActionPerformed(evt);
            }
        });

        AccountView.setText("View");
        AccountView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountViewActionPerformed(evt);
            }
        });

        AccountPrevious.setText("Previous");
        AccountPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountPreviousActionPerformed(evt);
            }
        });

        AccountNoView.setText("jTextField1");
        AccountNoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountNoViewActionPerformed(evt);
            }
        });

        jLabel1.setText("Account no:");

        javax.swing.GroupLayout AccountPannelLayout = new javax.swing.GroupLayout(AccountPannel);
        AccountPannel.setLayout(AccountPannelLayout);
        AccountPannelLayout.setHorizontalGroup(
            AccountPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccountPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPannelLayout.createSequentialGroup()
                        .addComponent(AccountNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AccountView, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AccountPannelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountNoView)))
                .addContainerGap())
        );
        AccountPannelLayout.setVerticalGroup(
            AccountPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountPannelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AccountPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountNoView, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AccountPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountNext)
                    .addComponent(AccountView)
                    .addComponent(AccountPrevious))
                .addContainerGap())
        );

        Deposit.setBorder(javax.swing.BorderFactory.createTitledBorder("Deposit"));
        Deposit.setName("BankAccounts"); // NOI18N

        DepositConfirm.setText("Confirm");
        DepositConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositConfirmActionPerformed(evt);
            }
        });

        DepositCancel.setText("cancel");
        DepositCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositCancelActionPerformed(evt);
            }
        });

        depositTextField.setText("jTextField1");

        jLabel2.setText("Amount");

        javax.swing.GroupLayout DepositLayout = new javax.swing.GroupLayout(Deposit);
        Deposit.setLayout(DepositLayout);
        DepositLayout.setHorizontalGroup(
            DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositLayout.createSequentialGroup()
                .addGroup(DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DepositLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DepositConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DepositCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DepositLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(depositTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DepositLayout.setVerticalGroup(
            DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositLayout.createSequentialGroup()
                .addGroup(DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepositConfirm)
                    .addComponent(DepositCancel))
                .addContainerGap())
        );

        Withdraw.setBorder(javax.swing.BorderFactory.createTitledBorder("Withdraw"));
        Withdraw.setName("BankAccounts"); // NOI18N

        WithdrawConfirm.setText("Confirm");
        WithdrawConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawConfirmActionPerformed(evt);
            }
        });

        WithdrawCancel.setText("cancel");
        WithdrawCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawCancelActionPerformed(evt);
            }
        });

        withdrawTextField.setText("jTextField1");

        jLabel3.setText("Amount:");

        javax.swing.GroupLayout WithdrawLayout = new javax.swing.GroupLayout(Withdraw);
        Withdraw.setLayout(WithdrawLayout);
        WithdrawLayout.setHorizontalGroup(
            WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithdrawLayout.createSequentialGroup()
                .addGroup(WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WithdrawLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WithdrawConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WithdrawCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WithdrawLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(withdrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        WithdrawLayout.setVerticalGroup(
            WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithdrawLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WithdrawConfirm)
                    .addComponent(WithdrawCancel))
                .addContainerGap())
        );

        QuitButton.setText("quit");
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        console.setEditable(false);
        console.setColumns(20);
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccountPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AccountPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccountPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountPreviousActionPerformed
        if (index > 0) {
            index--;
        } else {
            index = accountList.size() - 1;
        }
        AccountNoView.setText(accountList.get(index).getAccountNumber());
        console.setText("");
    }//GEN-LAST:event_AccountPreviousActionPerformed

    private void WithdrawCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawCancelActionPerformed
        withdrawTextField.setText("");
        viewInfomation();
    }//GEN-LAST:event_WithdrawCancelActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void AccountViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountViewActionPerformed
        viewInfomation();
    }//GEN-LAST:event_AccountViewActionPerformed

    private void AccountNoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountNoViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountNoViewActionPerformed

    private void AccountNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountNextActionPerformed
        if (index < (accountList.size() - 1)) {
            index++;
        }
        AccountNoView.setText(accountList.get(index).getAccountNumber());
        console.setText("");
    }//GEN-LAST:event_AccountNextActionPerformed

    private void DepositConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositConfirmActionPerformed
        console.setText("### Deposit ###\n");
        int amount = Integer.parseInt(depositTextField.getText());
        if (amount > 0) {
            deposit(amount);
        }
    }//GEN-LAST:event_DepositConfirmActionPerformed

    private void DepositCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositCancelActionPerformed
        depositTextField.setText("");
        viewInfomation();
    }//GEN-LAST:event_DepositCancelActionPerformed

    private void WithdrawConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawConfirmActionPerformed
        console.setText("### Withdraw ###\n");
        int amount = Integer.parseInt(withdrawTextField.getText());
        if (amount > 0) {
            withdraw(amount);
        }
    }//GEN-LAST:event_WithdrawConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountNext;
    private javax.swing.JTextField AccountNoView;
    private javax.swing.JPanel AccountPannel;
    private javax.swing.JButton AccountPrevious;
    private javax.swing.JButton AccountView;
    private javax.swing.JPanel Deposit;
    private javax.swing.JButton DepositCancel;
    private javax.swing.JButton DepositConfirm;
    private javax.swing.JButton QuitButton;
    private javax.swing.JPanel Withdraw;
    private javax.swing.JButton WithdrawCancel;
    private javax.swing.JButton WithdrawConfirm;
    private javax.swing.JTextArea console;
    private javax.swing.JTextField depositTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField withdrawTextField;
    // End of variables declaration//GEN-END:variables

    private ArrayList<BankAccount> accountList = new ArrayList<>();
    private final String DELIMITER = ",";
    private int index=0;
    
    public void loadData() {
        accountList.add( new BankAccount("Dave", "0", 100));
        accountList.add( new BankAccount("bob", "1", 1000));
        accountList.add( new BankAccount("ashley", "2", 5000));
    }
    
    public void viewInfomation() {
        String report = "";
        report += "### Account Information ###\n\n";
        report += String.format("%10s %s %n", "Name: ", accountList.get(index).getAccountName());
        report += String.format("%10s %s %n", "Number: ", accountList.get(index).getAccountNumber());
        report += String.format("%10s %s %n", "Balance: ", accountList.get(index).getAccountBalance());
        
        console.setText(report);
    }
    
    public void deposit(int amount) {
        double balance = accountList.get(index).getAccountBalance() + amount;
        accountList.get(index).setAccountBalance(balance);
        
        console.append(String.format(("%nDeposit of £ %d successfull. %nNew balance is %s %n"), amount, accountList.get(index).getFormattedBalance()));
    }
    
    public void withdraw(int amount) {
        double balance = accountList.get(index).getAccountBalance() - amount;
        accountList.get(index).setAccountBalance(balance);
        
        console.append(String.format(("%nWithdraw of £ %d successfull. %nNew balance is %s %n"), amount, accountList.get(index).getFormattedBalance()));
    }
}

